server:
  port: 8080
logging:
  level:
    org.springframework: INFO
    com.qiang: DEBUG
spring:
  output:
    ansi:
      enabled: always
  writeDataSource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.173.85:3306/db_area?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootMLE2018
  readDataSource:
    readsize: 1
    read0:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.37.150.51:3306/db_area?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: rootMle2018

#    read1:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://114.55.34.84:3306/db_area?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: rootYwd
  aop:
    auto: true
    proxy-target-class: true